const zlib=require('zlib'),fs=require('fs');
function decodeAny(p){const b=fs.readFileSync(p);const W=b.readUInt32BE(16),H=b.readUInt32BE(20),bd=b[24],ct=b[25];const ch=ct===6?4:ct===2?3:null;if(!ch||bd!==8)throw new Error('unsupported '+p+' ct'+ct);let off=8;const idat=[];while(off<b.length){const len=b.readUInt32BE(off);const t=b.toString('ascii',off+4,off+8);if(t==='IDAT')idat.push(b.subarray(off+8,off+8+len));off+=12+len;if(t==='IEND')break;}const raw=zlib.inflateSync(Buffer.concat(idat));const stride=W*ch,out=Buffer.alloc(H*stride);let prev=Buffer.alloc(stride),pp=0;for(let y=0;y<H;y++){const ft=raw[pp++];const cur=out.subarray(y*stride,y*stride+stride);raw.copy(cur,0,pp,pp+stride);pp+=stride;for(let x=0;x<stride;x++){const a=x>=ch?cur[x-ch]:0,bb=prev[x],c=x>=ch?prev[x-ch]:0;let v=cur[x];switch(ft){case 1:v=(v+a)&255;break;case 2:v=(v+bb)&255;break;case 3:v=(v+((a+bb)>>1))&255;break;case 4:{const q=a+bb-c,pa=Math.abs(q-a),pb=Math.abs(q-bb),pc=Math.abs(q-c);v=(v+(pa<=pb&&pa<=pc?a:pb<=pc?bb:c))&255;break;}}cur[x]=v;}prev=cur;}return{W,H,ch,data:out};}
function rgb2hsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b);let h,s,l=(mx+mn)/2;if(mx===mn){h=s=0;}else{const d=mx-mn;s=l>0.5?d/(2-mx-mn):d/(mx+mn);switch(mx){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4;}h/=6;}return[h*360,s,l];}
function stat(p,label){const {W,H,ch,data}=decodeAny(p);let n=0,sl=0,ss=0,shx=0,shy=0;const lum=[];for(let i=0;i<W*H;i++){const r=data[i*ch],g=data[i*ch+1],b=data[i*ch+2];const a=ch===4?data[i*ch+3]:255;if(a<200)continue;// 黒背景/紫背景・薄色を除外
  if(r<20&&g<20&&b<20)continue; if(r>150&&g<90&&b>150)continue; const[h,s,l]=rgb2hsl(r,g,b);if(l<0.06||l>0.97)continue;n++;sl+=l;ss+=s;shx+=Math.cos(h*Math.PI/180);shy+=Math.sin(h*Math.PI/180);lum.push(l);}
  lum.sort((a,b)=>a-b);const hue=(Math.atan2(shy/n,shx/n)*180/Math.PI+360)%360;
  console.log(label.padEnd(26),'px',String(n).padStart(7),' meanL',(sl/n).toFixed(3),' meanS',(ss/n).toFixed(3),' hue',hue.toFixed(0).padStart(3),' L10%',lum[(n*0.1)|0].toFixed(2),'L90%',lum[(n*0.9)|0].toFixed(2));}
const A='renderer/assets/ニシアフ/',M='renderer/assets/モーション/';
console.log('=== GREEN ===');stat(A+'最終進化緑.png','idle 最終進化緑');stat(M+'ニシアフ最終進化あくび1.png','yawn あくび1(green)');
console.log('=== BLUE ===');stat(A+'最終進化青.png','idle 最終進化青');stat(M+'ニシアフ最終進化あくび2.png','yawn あくび2(blue)');
console.log('=== GOLD ===');stat(A+'最終進化金.png','idle 最終進化金');stat(M+'ニシアフ最終進化あくび3.png','yawn あくび3(gold)');
